import { useState } from 'react';
import { useArchitectStore } from '../store/architectStore';
import { architectApi } from '../api/architect';
import Button from '../components/UI/Button';
import Card from '../components/UI/Card';
import CodeBlock from '../components/CodeBlock/CodeBlock';
import MermaidDiagram from '../components/Mermaid/MermaidDiagram';

const SAMPLE_CHALLENGES = [
  {
    challenge: 'カスタマーサポートの自動化を実現したい。FAQへの自動回答と、複雑な問い合わせは人間にエスカレーションする仕組みが必要。',
    industry: 'EC',
    constraints: ['日本語対応必須', '既存のZendeskと連携'],
  },
  {
    challenge: 'データ分析ワークフローの自動化。データ収集、前処理、分析、レポート生成を自動化し、異常値検出時はアラートを送信したい。',
    industry: '製造業',
    constraints: ['既存のBI toolと連携', 'リアルタイム処理'],
  },
  {
    challenge: '契約書レビューの効率化。契約書から重要条項を抽出し、リスク評価を行い、弁護士にレビュー依頼する仕組みを作りたい。',
    industry: '法律',
    constraints: ['高精度が必須', '機密情報の保護'],
  },
];

export default function ArchitectPage() {
  const { result, isLoading, error, setResult, setLoading, setError, clear } = useArchitectStore();
  const [businessChallenge, setBusinessChallenge] = useState('');
  const [industry, setIndustry] = useState('');
  const [constraints, setConstraints] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!businessChallenge.trim() || isLoading) return;

    setError(null);
    setLoading(true);

    try {
      const response = await architectApi.generate({
        business_challenge: businessChallenge.trim(),
        industry: industry.trim() || undefined,
        constraints: constraints.trim() ? constraints.split('\n').map(c => c.trim()).filter(Boolean) : undefined,
      });

      setResult(response);
    } catch (err) {
      setError(err instanceof Error ? err.message : '構成案の生成に失敗しました');
    } finally {
      setLoading(false);
    }
  };

  const handleSampleChallenge = (sample: typeof SAMPLE_CHALLENGES[0]) => {
    setBusinessChallenge(sample.challenge);
    setIndustry(sample.industry);
    setConstraints(sample.constraints.join('\n'));
  };

  const handleDownload = () => {
    if (!result) return;

    const markdown = `# LangGraph構成案

## ビジネス課題
${businessChallenge}

${industry ? `**業界**: ${industry}\n` : ''}
${constraints ? `**制約条件**:\n${constraints.split('\n').map(c => `- ${c}`).join('\n')}\n` : ''}

---

## 課題分析

### 要約
${result.challenge_analysis.summary}

### 主要要件
${result.challenge_analysis.key_requirements.map(r => `- ${r}`).join('\n')}

### 推奨アプローチ
${result.challenge_analysis.suggested_approach}

### LangGraphが適している理由
${result.challenge_analysis.langgraph_fit_reason}

---

## アーキテクチャ

### Mermaid図
\`\`\`mermaid
${result.architecture.mermaid_diagram}
\`\`\`

### ノード説明
${result.architecture.node_descriptions.map(node => `
#### ${node.name} (${node.node_id})
**目的**: ${node.purpose}
${node.description ? `**詳細**: ${node.description}\n` : ''}**入力**: ${node.inputs.join(', ')}
**出力**: ${node.outputs.join(', ')}
`).join('\n')}

### エッジ説明
${result.architecture.edge_descriptions.map(edge => `
- **${edge.from_node} → ${edge.to_node}**${edge.condition ? ` (条件: ${edge.condition})` : ''}: ${edge.description}
`).join('\n')}

---

## コード例

${result.code_example.explanation}

\`\`\`${result.code_example.language}
${result.code_example.code}
\`\`\`

---

## ビジネス向け説明

${result.business_explanation}

---

## 実装の注意点

${result.implementation_notes.map(note => `- ${note}`).join('\n')}

---

*Generated by LangGraph Catalyst*
*Model: ${result.metadata.model}*
*Response Time: ${result.metadata.response_time.toFixed(2)}s*
*Tokens Used: ${result.metadata.tokens_used}*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `langgraph-architecture-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-6 py-12">
      {/* Header */}
      <div className="mb-12 animate-fade-in">
        <div className="accent-line-top mb-6" />
        <h1 className="text-5xl font-bold mb-4 leading-tight">
          <span className="bg-gradient-to-r from-[var(--color-accent-secondary)] to-purple-600 text-transparent bg-clip-text">
            構成案生成
          </span>
        </h1>
        <p className="text-xl text-[var(--color-text-secondary)] max-w-3xl leading-relaxed">
          ビジネス課題を入力すると、LangGraphによる解決策を提案します。Mermaid図とコード例で具体的な実装イメージを提供します。
        </p>

        {result && (
          <div className="mt-4 flex space-x-4">
            <Button variant="outline" size="sm" onClick={clear}>
              新しい課題を入力
            </Button>
            <Button variant="primary" size="sm" onClick={handleDownload}>
              Markdownをダウンロード
            </Button>
          </div>
        )}
      </div>

      {!result ? (
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Input Form */}
          <div className="lg:col-span-2">
            <Card>
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <label htmlFor="challenge" className="block text-sm font-bold mb-2 text-[var(--color-accent-primary)]">
                    ビジネス課題 <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    id="challenge"
                    value={businessChallenge}
                    onChange={(e) => setBusinessChallenge(e.target.value)}
                    placeholder="解決したいビジネス課題を具体的に記述してください..."
                    className="w-full px-4 py-3 bg-[var(--color-bg-tertiary)] border border-[var(--color-border)] text-[var(--color-text-primary)] placeholder-[var(--color-text-tertiary)] focus:border-[var(--color-accent-primary)] focus:outline-none transition-colors font-mono"
                    rows={5}
                    disabled={isLoading}
                    required
                  />
                </div>

                <div>
                  <label htmlFor="industry" className="block text-sm font-bold mb-2 text-[var(--color-accent-warm)]">
                    業界（任意）
                  </label>
                  <input
                    type="text"
                    id="industry"
                    value={industry}
                    onChange={(e) => setIndustry(e.target.value)}
                    placeholder="例: EC, 製造業, 金融, 医療など"
                    className="w-full px-4 py-3 bg-[var(--color-bg-tertiary)] border border-[var(--color-border)] text-[var(--color-text-primary)] placeholder-[var(--color-text-tertiary)] focus:border-[var(--color-accent-primary)] focus:outline-none transition-colors font-mono"
                    disabled={isLoading}
                  />
                </div>

                <div>
                  <label htmlFor="constraints" className="block text-sm font-bold mb-2 text-[var(--color-accent-warm)]">
                    制約条件（任意、1行に1つ）
                  </label>
                  <textarea
                    id="constraints"
                    value={constraints}
                    onChange={(e) => setConstraints(e.target.value)}
                    placeholder="例:&#10;日本語対応必須&#10;既存システムとの連携&#10;高精度が必須"
                    className="w-full px-4 py-3 bg-[var(--color-bg-tertiary)] border border-[var(--color-border)] text-[var(--color-text-primary)] placeholder-[var(--color-text-tertiary)] focus:border-[var(--color-accent-primary)] focus:outline-none transition-colors font-mono"
                    rows={4}
                    disabled={isLoading}
                  />
                </div>

                {error && (
                  <div className="p-3 bg-red-900/20 border border-red-500/50 text-red-400 text-sm">
                    ⚠️ {error}
                  </div>
                )}

                <Button
                  type="submit"
                  variant="primary"
                  size="lg"
                  className="w-full"
                  isLoading={isLoading}
                  disabled={!businessChallenge.trim() || isLoading}
                >
                  {isLoading ? '構成案を生成中...' : '構成案を生成'}
                </Button>
              </form>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            <Card>
              <h3 className="text-xl font-bold mb-4 flex items-center">
                <span className="text-2xl mr-2">💡</span>
                サンプル課題
              </h3>
              <div className="space-y-3">
                {SAMPLE_CHALLENGES.map((sample, idx) => (
                  <button
                    key={idx}
                    onClick={() => handleSampleChallenge(sample)}
                    disabled={isLoading}
                    className="w-full text-left px-4 py-3 bg-[var(--color-bg-tertiary)] border border-[var(--color-border)] hover:border-[var(--color-accent-secondary)] transition-all disabled:opacity-50"
                  >
                    <div className="text-sm text-[var(--color-text-primary)] mb-2">
                      {sample.challenge.substring(0, 80)}...
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <span className="px-2 py-1 text-xs bg-[var(--color-accent-secondary)]/20 text-[var(--color-accent-secondary)] border border-[var(--color-accent-secondary)]/30">
                        {sample.industry}
                      </span>
                      {sample.constraints.slice(0, 2).map((c, i) => (
                        <span
                          key={i}
                          className="px-2 py-1 text-xs bg-[var(--color-bg-primary)] text-[var(--color-text-tertiary)] border border-[var(--color-border)]"
                        >
                          {c.substring(0, 15)}...
                        </span>
                      ))}
                    </div>
                  </button>
                ))}
              </div>
            </Card>

            <Card className="mt-6" hover={false}>
              <h3 className="text-lg font-bold mb-3 text-[var(--color-accent-primary)]">
                🏗️ 出力内容
              </h3>
              <ul className="space-y-2 text-sm text-[var(--color-text-secondary)]">
                <li>✓ 課題分析と要件定義</li>
                <li>✓ Mermaid図によるフロー可視化</li>
                <li>✓ Pythonコード例</li>
                <li>✓ ビジネス向け説明</li>
                <li>✓ 実装の注意点</li>
              </ul>
            </Card>
          </div>
        </div>
      ) : (
        /* Results Display */
        <div className="space-y-8">
          {/* Challenge Analysis */}
          <Card className="animate-fade-in">
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <span className="text-3xl mr-3">🔍</span>
              課題分析
            </h2>

            <div className="space-y-4">
              <div>
                <h3 className="text-lg font-bold mb-2 text-[var(--color-accent-primary)]">要約</h3>
                <p className="text-[var(--color-text-secondary)] leading-relaxed">
                  {result.challenge_analysis.summary}
                </p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2 text-[var(--color-accent-primary)]">主要要件</h3>
                <ul className="space-y-1 text-[var(--color-text-secondary)]">
                  {result.challenge_analysis.key_requirements.map((req, idx) => (
                    <li key={idx} className="flex items-start">
                      <span className="text-[var(--color-accent-warm)] mr-2">▸</span>
                      {req}
                    </li>
                  ))}
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2 text-[var(--color-accent-primary)]">推奨アプローチ</h3>
                <p className="text-[var(--color-text-secondary)] leading-relaxed">
                  {result.challenge_analysis.suggested_approach}
                </p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2 text-[var(--color-accent-secondary)]">
                  LangGraphが適している理由
                </h3>
                <p className="text-[var(--color-text-secondary)] leading-relaxed">
                  {result.challenge_analysis.langgraph_fit_reason}
                </p>
              </div>
            </div>
          </Card>

          {/* Architecture Diagram */}
          <Card className="animate-fade-in" style={{ animationDelay: '100ms' }}>
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <span className="text-3xl mr-3">📊</span>
              アーキテクチャ図
            </h2>
            <MermaidDiagram chart={result.architecture.mermaid_diagram} />

            {/* Node Descriptions */}
            <div className="mt-6">
              <h3 className="text-lg font-bold mb-3 text-[var(--color-accent-primary)]">ノード説明</h3>
              <div className="grid md:grid-cols-2 gap-4">
                {result.architecture.node_descriptions.map((node, idx) => (
                  <div
                    key={idx}
                    className="bg-[var(--color-bg-tertiary)] border border-[var(--color-border)] p-4 rounded"
                  >
                    <div className="font-bold text-[var(--color-accent-warm)] mb-1">
                      {node.name} ({node.node_id})
                    </div>
                    <div className="text-sm text-[var(--color-text-secondary)] mb-2">
                      {node.purpose}
                    </div>
                    {node.description && (
                      <div className="text-xs text-[var(--color-text-tertiary)] mb-2">
                        {node.description}
                      </div>
                    )}
                    <div className="text-xs text-[var(--color-text-tertiary)]">
                      <div>入力: {node.inputs.join(', ')}</div>
                      <div>出力: {node.outputs.join(', ')}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Card>

          {/* Code Example */}
          <Card className="animate-fade-in" style={{ animationDelay: '200ms' }}>
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <span className="text-3xl mr-3">💻</span>
              実装コード例
            </h2>
            <p className="text-[var(--color-text-secondary)] mb-4 leading-relaxed">
              {result.code_example.explanation}
            </p>
            <CodeBlock
              code={result.code_example.code}
              language={result.code_example.language}
            />
          </Card>

          {/* Business Explanation */}
          <Card className="animate-fade-in" style={{ animationDelay: '300ms' }}>
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <span className="text-3xl mr-3">📝</span>
              ビジネス向け説明
            </h2>
            <p className="text-[var(--color-text-secondary)] leading-relaxed whitespace-pre-wrap">
              {result.business_explanation}
            </p>
          </Card>

          {/* Implementation Notes */}
          <Card className="animate-fade-in" style={{ animationDelay: '400ms' }}>
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <span className="text-3xl mr-3">⚠️</span>
              実装の注意点
            </h2>
            <ul className="space-y-2 text-[var(--color-text-secondary)]">
              {result.implementation_notes.map((note, idx) => (
                <li key={idx} className="flex items-start">
                  <span className="text-[var(--color-accent-warm)] mr-2">▸</span>
                  {note}
                </li>
              ))}
            </ul>
          </Card>

          {/* Metadata */}
          <div className="text-xs text-[var(--color-text-tertiary)] text-center">
            Model: {result.metadata.model} • Response Time: {result.metadata.response_time.toFixed(2)}s • Tokens: {result.metadata.tokens_used}
          </div>
        </div>
      )}
    </div>
  );
}
